[VectorDB] Feature: Add upstash vector support
agno-agi/agno pull request #1671
Opened 2024-12-31 18:40 UTC by Abdusshh

## Description

- **Summary of changes**: Add Upstash Vector as a VectorDB
- **Environment or dependencies**: Added `upstash_vector` to `pyproject.toml`

## Type of change

Please check the options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Model update
- [ ] Infrastructure change

## Checklist

- [ ] My code follows Phidata's style guidelines and best practices
- [ ] I have performed a self-review of my code
- [ ] I have added docstrings and comments for complex logic
- [ ] My changes generate no new warnings or errors
- [ ] I have added cookbook examples for my new addition (if needed)
- [ ] I have updated requirements.txt/pyproject.toml (if needed)
- [ ] I have verified my changes in a clean environment

2025-01-06 12:28 UTC, manthanguptaa commented on cookbook/vectordb/upstash.py
Add steps on how to run upstash locally

2025-01-06 12:32 UTC, manthanguptaa commented on phi/vectordb/upstash/upstash.py
> +        kwargs (Dict[str, Any]): Additional keyword arguments.
redundancy

2025-01-06 12:32 UTC, manthanguptaa commented on phi/vectordb/upstash/upstash.py
> +        pass
no implementation for this?

2025-01-06 12:38 UTC, manthanguptaa requested changes
<img width="1251" alt="Screenshot 2025-01-06 at 6 08 38 PM" src="https://github.com/user-attachments/assets/68d70025-6ed9-4ca6-965c-306dc5dfd03d" />

Code doesn't seem to be working

2025-01-06 12:53 UTC, Abdusshh commented on phi/vectordb/upstash/upstash.py
> +        pass
Yes, index creation and deletion happen via Upstash Console.

2025-01-06 12:55 UTC, Abdusshh commented
Did you create an index before running the code

2025-01-06 12:58 UTC, Abdusshh commented on phi/vectordb/upstash/upstash.py
> +        kwargs (Dict[str, Any]): Additional keyword arguments.
I used the same structure as PineconeDB, now I will delete the attributes

2025-01-06 12:59 UTC, Abdusshh commented on cookbook/vectordb/upstash.py
Wdym? Like the cookbook example?

2025-01-07 05:08 UTC, manthanguptaa commented on cookbook/vectordb/upstash.py
@Abdusshh add steps on how to run upstash as a doc string on top of the cookbook

2025-01-07 06:00 UTC, Abdusshh commented on cookbook/vectordb/upstash.py
Added similar to milvus example

2025-01-07 06:01 UTC, Abdusshh commented on phi/vectordb/upstash/upstash.py
> +        pass
Updated the logger messages to make them clearer @manthanguptaa

2025-01-16 09:31 UTC, Abdusshh commented
Hey @manthanguptaa, I believe the code is working fine. Did you have the chance to look at it again based on my previous comment.

2025-01-30 14:19 UTC, Abdusshh commented
I guess phi is no more, should I move this to agno?

2025-02-03 11:15 UTC, manthanguptaa commented
Hey @enesgules! yes, we have rebranded to Agno and would love this PR to be ported to it. Thanks

2025-02-11 09:50 UTC, closed without merging